### ISSUE TITLE
Updater doesn't overwrite previous installer

### ISSUE THREAD

**Issue by gregkare** [cryptocat/cryptocat#42] opened 2016-04-04 21:18 UTC
This looks similar to #5, which was closed as invalid.

I'm on OS X 10.11.4. I was running Cryptocat 3.0.18 until today and manually checked for updates. I selected my Downloads folder, the archive wasn't overwritten so I ended up installing the same version again. I realised it because I got prompted for the update again. After deleting both the .zip and the .pkg and updating again I could install the current version by unzipping the archive and running the installer

**Comment by kaepora** [comment] 2016-04-06 14:00
I don't want to judge prematurely, but I can't reproduce this. It seems like user error. I'm closing the issue for now, but **if it happens again on the next update**, please let me know and I will re-investigate. Thanks.

**Closed** 2016-04-06 14:00 UTC
Labels: question

**Comment by gregkare** [comment] 2016-04-14 13:25
Hi, it just happened again.

Updating from 3.0.27. I have the previous archive in my Downloads folder (Cryptocat-darwin-x64.zip). The updater asks me to overwrite the file, I confirm, it downloads and the previous archive is still there. Once again I've worked around it by deleting Cryptocat-darwin-x64.zip before starting the update process
