### ISSUE TITLE
Add option for proxy settings

### ISSUE THREAD

**Issue by jackpit110** [cryptocat/cryptocat#153] opened 2016-06-16 09:26 UTC
I know this is not help forum and  I know How to send my traffic over tor with use tools like proxyfire or proxychains !
But actualy this is a request to add option for Cryptocat for proxy settings like tor or other proxy servers
Cryptocat is a great tool for secure chat and Everyone know that Tor is very safe network
So when your time is free please add this option to cryptocat
Regards

**Comment by kaepora** [comment] 2016-06-16 11:40
In the event of repeat offenses where a user either keeps posting support requests, invalid issues or duplicates, my policy is to ban that user.

This is the third issue you've posted in 24 hours. Your first was invalid, the second was a support request, and this is a duplicate of #10. You are banned from opening future issues.

**Closed by kaepora** 2016-06-16 11:40 UTC
