### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by OlivierCuyp** [cryptocat/cryptocat#20] opened 2016-03-30 11:58 UTC
Hi,

Just installed the Beta, my computer went in sleep mode.
When I waked it up, I got the following error :

```
Uncaught Exception:
Error: Object has been destroyed
    at Error (native)
    at EventEmitter.<anonymous> (/Applications/Cryptocat.app/Contents/Resources/app.asar/app.js:332:15)
    at emitTwo (events.js:92:20)
    at EventEmitter.emit (events.js:172:7)
```

**Comment by kaepora** [comment] 2016-03-30 11:59
Thank you, this seems to be a duplicate of #18. Both errors seem to happen when recovering from sleep mode, and I believe only on OS X.

**Closed by kaepora** 2016-03-30 11:59 UTC
Labels: duplicate
