### ISSUE TITLE
Failed to install on my Win 7 32 laptop

### ISSUE THREAD

**Issue by IpsmLorem** [cryptocat/cryptocat#198] opened 2016-09-11 13:31 UTC
Something went wrong when I tried to install cryptocat on my Win 7 32 laptop.

The log ([cryptocat_uglog.txt](https://github.com/cryptocat/cryptocat/files/466000/cryptocat_uglog.txt) ) says:
`Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Impossible de trouver une partie du chemin d'accès 'C:\Users\Lorem\AppData\Local\Cryptocat\packages\.betaId'.`

I tried to create the file "by hand", with the same user with notepad and there is no problem with File System rights.

I hope that could help you to improve your software.

**Comment by nimd4** [comment] 2016-09-12 00:26
Hi, check it out @https://github.com/cryptocat/cryptocat/issues/33

> I am sorry to report that after investigating this issue, it appears that a fix is not currently possible since the Electron framework's Squirrel auto-updater is 64-bit only on Windows. As such there will be no 32-bit releases of Cryptocat.
> @kaepora kaepora closed this on Jul 11
> @kaepora kaepora locked and limited conversation to collaborators on Jul 11

Btw., there's nothing to _improve_ upon, 32-bit is a thing of past..:)

**Comment by kaepora** [comment] 2016-09-12 07:32
@nimd4 Has been banned from posting on future issues pursuant to this comment also comments on #199 and #154.

**Comment by kaepora** [comment] 2016-09-12 09:27
Duplicate of #33.

**Closed by kaepora** 2016-09-12 09:27 UTC
Labels: invalid
