### ISSUE TITLE
[UX] Make pasted links clickable

### ISSUE THREAD

**Issue by ggramaize** [cryptocat/cryptocat#52] opened 2016-04-10 17:06 UTC
Tested version: 3.0.27 
Reproduction path:
1. Open chat window
2. Post a valid URL

Expected bahaviour:
When posting an URL, the url should become clickable once it is in the chat history

**Comment by kaepora** [comment] 2016-04-10 18:39
Duplicate of #16. Once again, please check for duplicates before opening issues. Remember and respect that I maintain Cryptocat on my own time.

**Closed by kaepora** 2016-04-10 18:39 UTC
Labels: duplicate
