### ISSUE TITLE
Easier opening of links

### ISSUE THREAD

**Issue by 4getit** [cryptocat/cryptocat#206] opened 2016-09-26 17:37 UTC
Right now, a link/url cannot be opened by clicking on it. The only way I can think of is selecting the link, then copy it and then paste it wherever needed.
Is it possible to make that easier?

**Comment by kathysue** [comment] 2016-10-06 23:05
I agree

**Comment by kaepora** [comment] 2016-12-19 11:14
Duplicate of #16.

**Closed by kaepora** 2016-12-19 11:14 UTC
Labels: duplicate
